# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: 110350867+gurubazawada@users.noreply.github.com
author_name: gurubazawada
preset_name: starter
project_name: AgriGuard-frontend

